from aiogram.types import ReplyKeyboardMarkup, KeyboardButton

b1 = KeyboardButton('/profile')
b3 = KeyboardButton('/tasks')
b4 = KeyboardButton('/list')
b5 = KeyboardButton('/config')
b6 = KeyboardButton('да')
b7 = KeyboardButton('отмена')
b8 = KeyboardButton('/top_1')

a1 = KeyboardButton(f'/задание_1планирование')
a2 = KeyboardButton(f'/задание_2планирование')
a3 = KeyboardButton(f'/задание_3планирование')
a4 = KeyboardButton(f'/задание_4планирование')
a5 = KeyboardButton(f'/задание_1управление')
a6 = KeyboardButton(f'/задание_2управление')
a7 = KeyboardButton(f'/задание_3управление')
a8 = KeyboardButton(f'/задание_4управление')
a9 = KeyboardButton(f'/задание_1коммуникации')
a10 = KeyboardButton(f'/задание_2коммуникации')
a11 = KeyboardButton(f'/задание_3коммуникации')
a12 = KeyboardButton(f'/задание_4коммуникации')
a13 = KeyboardButton(f'/задание_1анализ')
a14 = KeyboardButton(f'/задание_2анализ')
a15 = KeyboardButton(f'/задание_3анализ')
a16 = KeyboardButton(f'назад')

kb_client = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True)
kb_client_2 = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True)
kb_client_3 = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True)

kb_client.add(b1).insert(b8).add(b3).insert(b4).add(b5)
kb_client_2.add(b6).add(b7)
kb_client_3.add(a1).insert(a2).insert(a3).insert(a4).add(a5).insert(a6).insert(a7).insert(a8).add(a9).insert(a10).insert(a11).insert(a12).add(a13).insert(a14).insert(a15).add(a16)
